// <auto-generated />
using System;
using Infrastructure.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Appointments.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OfferingId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Domain.Assignments.AssignmentRegistry", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("StoreId");

                    b.ToTable("AssignmentRegistries", (string)null);
                });

            modelBuilder.Entity("Domain.Calendars.StoreCalendar", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("StoreId");

                    b.ToTable("StoreCalendars", (string)null);
                });

            modelBuilder.Entity("Domain.Catalogs.StoreCatalog", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("StoreId");

                    b.ToTable("StoreCatalogs", (string)null);
                });

            modelBuilder.Entity("Domain.Professionals.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Professionals", (string)null);
                });

            modelBuilder.Entity("Domain.Rosters.Staff", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("StoreId");

                    b.ToTable("Staff", (string)null);
                });

            modelBuilder.Entity("Domain.Schedules.ProfessionalSchedule", b =>
                {
                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.HasKey("ProfessionalId");

                    b.ToTable("ProfessionalSchedules", (string)null);
                });

            modelBuilder.Entity("Domain.Stores.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Appointments.Appointment", b =>
                {
                    b.HasOne("Domain.Professionals.Professional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Stores.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.Common.ValueObjects.UtcDateTime", "CanceledAt", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("CanceledAt");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Duration", "Duration", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<int>("Minutes")
                                .HasColumnType("int")
                                .HasColumnName("DurationMinutes");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.UtcDateTime", "StartAt", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartAt");

                            b1.HasKey("AppointmentId");

                            b1.HasIndex("Value");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.OwnsOne("Domain.Appointments.ValueObjects.Notes", "Notes", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Notes");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("Appointments");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("CanceledAt");

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("Notes")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("StartAt")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Assignments.AssignmentRegistry", b =>
                {
                    b.HasOne("Domain.Stores.Store", null)
                        .WithOne()
                        .HasForeignKey("Domain.Assignments.AssignmentRegistry", "StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Assignments.ValueObjects.Assignment", "_assignments", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.Property<int>("OfferingId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("OfferingId"));

                            b1.HasKey("StoreId", "ProfessionalId", "OfferingId");

                            b1.HasIndex("ProfessionalId");

                            b1.ToTable("Assignments", (string)null);

                            b1.HasOne("Domain.Professionals.Professional", null)
                                .WithMany()
                                .HasForeignKey("ProfessionalId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.Navigation("_assignments");
                });

            modelBuilder.Entity("Domain.Calendars.StoreCalendar", b =>
                {
                    b.HasOne("Domain.Stores.Store", null)
                        .WithOne()
                        .HasForeignKey("Domain.Calendars.StoreCalendar", "StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("StoreCalendarException", "Exceptions", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.HasKey("StoreId", "Date");

                            b1.ToTable("StoreCalendarExceptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsMany("StoreCalendarExceptionTimeRanges", "TimeRanges", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("date");

                                    b2.Property<TimeSpan>("End")
                                        .HasColumnType("time")
                                        .HasColumnName("End");

                                    b2.Property<TimeSpan>("Start")
                                        .HasColumnType("time")
                                        .HasColumnName("Start");

                                    b2.Property<int>("StoreId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("StoreId", "Date");

                                    b2.ToTable("StoreExceptionTimeRanges", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StoreId", "Date");
                                });

                            b1.Navigation("TimeRanges");
                        });

                    b.OwnsMany("StoreCalendarWorkingDay", "WorkingDays", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<int>("Day")
                                .HasColumnType("int");

                            b1.HasKey("StoreId", "Day");

                            b1.ToTable("StoreCalendarWorkingDays", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsMany("StoreCalendarWorkingDayTimeRange", "TimeRanges", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("Day")
                                        .HasColumnType("int");

                                    b2.Property<TimeSpan>("End")
                                        .HasColumnType("time")
                                        .HasColumnName("End");

                                    b2.Property<TimeSpan>("Start")
                                        .HasColumnType("time")
                                        .HasColumnName("Start");

                                    b2.Property<int>("StoreId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("StoreId", "Day");

                                    b2.ToTable("StoreCalendarWorkingDayTimeRanges", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StoreId", "Day");
                                });

                            b1.Navigation("TimeRanges");
                        });

                    b.Navigation("Exceptions");

                    b.Navigation("WorkingDays");
                });

            modelBuilder.Entity("Domain.Catalogs.StoreCatalog", b =>
                {
                    b.HasOne("Domain.Stores.Store", null)
                        .WithOne()
                        .HasForeignKey("Domain.Catalogs.StoreCatalog", "StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Catalogs.Entities.Offering", "Offerings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("StoreId");

                            b1.ToTable("Offerings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsOne("Domain.Common.ValueObjects.Duration", "Duration", b2 =>
                                {
                                    b2.Property<int>("OfferingId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Minutes")
                                        .HasColumnType("int")
                                        .HasColumnName("DurationMinutes");

                                    b2.HasKey("OfferingId");

                                    b2.ToTable("Offerings");

                                    b2.WithOwner()
                                        .HasForeignKey("OfferingId");
                                });

                            b1.OwnsOne("Domain.Common.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<int>("OfferingId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("decimal(18,2)")
                                        .HasColumnName("PriceAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)")
                                        .HasColumnName("PriceCurrency");

                                    b2.HasKey("OfferingId");

                                    b2.ToTable("Offerings");

                                    b2.WithOwner()
                                        .HasForeignKey("OfferingId");
                                });

                            b1.OwnsOne("Domain.Catalogs.ValueObjects.Description", "Description", b2 =>
                                {
                                    b2.Property<int>("OfferingId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)")
                                        .HasColumnName("Description");

                                    b2.HasKey("OfferingId");

                                    b2.ToTable("Offerings");

                                    b2.WithOwner()
                                        .HasForeignKey("OfferingId");
                                });

                            b1.OwnsOne("Domain.Catalogs.ValueObjects.OfferingName", "Name", b2 =>
                                {
                                    b2.Property<int>("OfferingId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("Name");

                                    b2.HasKey("OfferingId");

                                    b2.ToTable("Offerings");

                                    b2.WithOwner()
                                        .HasForeignKey("OfferingId");
                                });

                            b1.Navigation("Description")
                                .IsRequired();

                            b1.Navigation("Duration")
                                .IsRequired();

                            b1.Navigation("Name")
                                .IsRequired();

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.Navigation("Offerings");
                });

            modelBuilder.Entity("Domain.Professionals.Professional", b =>
                {
                    b.OwnsOne("Domain.Common.ValueObjects.UtcDateTime", "DeletedAt", b1 =>
                        {
                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAt");

                            b1.HasKey("ProfessionalId");

                            b1.ToTable("Professionals");

                            b1.WithOwner()
                                .HasForeignKey("ProfessionalId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.HasKey("ProfessionalId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Professionals");

                            b1.WithOwner()
                                .HasForeignKey("ProfessionalId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("ProfessionalId");

                            b1.ToTable("Professionals");

                            b1.WithOwner()
                                .HasForeignKey("ProfessionalId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("PhoneCountryCode");

                            b1.Property<string>("NationalNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PhoneNationalNumber");

                            b1.HasKey("ProfessionalId");

                            b1.HasIndex("CountryCode", "NationalNumber")
                                .IsUnique();

                            b1.ToTable("Professionals");

                            b1.WithOwner()
                                .HasForeignKey("ProfessionalId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.TaxIdentificationNumber", "TaxIdNumber", b1 =>
                        {
                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("TaxCountryCode");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TaxIdNumber");

                            b1.HasKey("ProfessionalId");

                            b1.HasIndex("CountryCode", "Value")
                                .IsUnique();

                            b1.ToTable("Professionals");

                            b1.WithOwner()
                                .HasForeignKey("ProfessionalId");
                        });

                    b.Navigation("DeletedAt");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("TaxIdNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Rosters.Staff", b =>
                {
                    b.HasOne("Domain.Stores.Store", null)
                        .WithOne()
                        .HasForeignKey("Domain.Rosters.Staff", "StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Rosters.Entities.StaffMember", "Members", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.HasKey("StoreId", "ProfessionalId");

                            b1.HasIndex("ProfessionalId");

                            b1.ToTable("StaffMembers", (string)null);

                            b1.HasOne("Domain.Professionals.Professional", null)
                                .WithMany()
                                .HasForeignKey("ProfessionalId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.OwnsMany("Domain.Rosters.ValueObjects.RoleAssignment", "Roles", b2 =>
                                {
                                    b2.Property<int>("StoreId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ProfessionalId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Role")
                                        .HasColumnType("int");

                                    b2.HasKey("StoreId", "ProfessionalId", "Role");

                                    b2.ToTable("StaffMemberRoles", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("StoreId", "ProfessionalId");
                                });

                            b1.Navigation("Roles");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Schedules.ProfessionalSchedule", b =>
                {
                    b.HasOne("Domain.Professionals.Professional", null)
                        .WithOne()
                        .HasForeignKey("Domain.Schedules.ProfessionalSchedule", "ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Domain.Schedules.Entities.StaffCalendar", "Calendars", b1 =>
                        {
                            b1.Property<int>("ProfessionalId")
                                .HasColumnType("int");

                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.HasKey("ProfessionalId", "StoreId");

                            b1.HasIndex("StoreId");

                            b1.ToTable("StaffCalendars", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProfessionalId");

                            b1.HasOne("Domain.Stores.Store", null)
                                .WithMany()
                                .HasForeignKey("StoreId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.OwnsMany("StaffCalendarException", "Exceptions", b2 =>
                                {
                                    b2.Property<int>("ProfessionalId")
                                        .HasColumnType("int");

                                    b2.Property<int>("StoreId")
                                        .HasColumnType("int");

                                    b2.Property<DateOnly>("Date")
                                        .HasColumnType("date");

                                    b2.HasKey("ProfessionalId", "StoreId", "Date");

                                    b2.ToTable("StaffCalendarExceptions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ProfessionalId", "StoreId");

                                    b2.OwnsMany("StaffCalendarExceptionTimeRange", "TimeRanges", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<DateOnly>("Date")
                                                .HasColumnType("date");

                                            b3.Property<TimeSpan>("End")
                                                .HasColumnType("time")
                                                .HasColumnName("End");

                                            b3.Property<int>("ProfessionalId")
                                                .HasColumnType("int");

                                            b3.Property<TimeSpan>("Start")
                                                .HasColumnType("time")
                                                .HasColumnName("Start");

                                            b3.Property<int>("StoreId")
                                                .HasColumnType("int");

                                            b3.HasKey("Id");

                                            b3.HasIndex("ProfessionalId", "StoreId", "Date");

                                            b3.ToTable("StaffCalendarExceptionTimeRanges", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("ProfessionalId", "StoreId", "Date");
                                        });

                                    b2.Navigation("TimeRanges");
                                });

                            b1.OwnsMany("StaffCalendarWorkingDay", "WorkingDays", b2 =>
                                {
                                    b2.Property<int>("ProfessionalId")
                                        .HasColumnType("int");

                                    b2.Property<int>("StoreId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Day")
                                        .HasColumnType("int");

                                    b2.HasKey("ProfessionalId", "StoreId", "Day");

                                    b2.ToTable("StaffCalendarWorkingDays", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ProfessionalId", "StoreId");

                                    b2.OwnsMany("StaffCalendarWorkingDayTimeRanges", "TimeRanges", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<int>("Day")
                                                .HasColumnType("int");

                                            b3.Property<TimeSpan>("End")
                                                .HasColumnType("time")
                                                .HasColumnName("End");

                                            b3.Property<int>("ProfessionalId")
                                                .HasColumnType("int");

                                            b3.Property<TimeSpan>("Start")
                                                .HasColumnType("time")
                                                .HasColumnName("Start");

                                            b3.Property<int>("StoreId")
                                                .HasColumnType("int");

                                            b3.HasKey("Id");

                                            b3.HasIndex("ProfessionalId", "StoreId", "Day");

                                            b3.ToTable("StaffCalendarWorkingDayTimeRanges", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("ProfessionalId", "StoreId", "Day");
                                        });

                                    b2.Navigation("TimeRanges");
                                });

                            b1.Navigation("Exceptions");

                            b1.Navigation("WorkingDays");
                        });

                    b.Navigation("Calendars");
                });

            modelBuilder.Entity("Domain.Stores.Store", b =>
                {
                    b.OwnsOne("Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("CountryCode");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Street");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.UtcDateTime", "ClosedAt", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("ClosedAt");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.HasKey("StoreId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("PhoneCountryCode");

                            b1.Property<string>("NationalNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PhoneNationalNumber");

                            b1.HasKey("StoreId");

                            b1.HasIndex("CountryCode", "NationalNumber")
                                .IsUnique();

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.TaxIdentificationNumber", "TaxIdNumber", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("TaxCountryCode");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TaxIdNumber");

                            b1.HasKey("StoreId");

                            b1.HasIndex("CountryCode", "Value")
                                .IsUnique();

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.OwnsOne("Domain.Stores.ValueObjects.StoreName", "Name", b1 =>
                        {
                            b1.Property<int>("StoreId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("StoreName");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("ClosedAt");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("TaxIdNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.OwnsOne("Domain.Common.ValueObjects.UtcDateTime", "DeletedAt", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DeletedAt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("nvarchar(320)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)")
                                .HasColumnName("PhoneCountryCode");

                            b1.Property<string>("NationalNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("PhoneNationalNumber");

                            b1.HasKey("UserId");

                            b1.HasIndex("CountryCode", "NationalNumber")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("DeletedAt");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
